export const styles = {
  container: "max-w-7xl mx-auto p-4 sm:p-8 bg-white min-h-screen",
  heading: "text-4xl font-bold text-gray-900 mb-8 border-b pb-4",
  searchSection: "bg-gray-50 p-6 rounded-lg shadow-sm mb-8",
  searchLabel: "text-lg font-semibold text-gray-700 mb-2",
  searchTerm: "text-sm text-gray-600 mb-3",
  searchInput: "w-full sm:w-64 border border-gray-300 rounded-md px-4 py-2 mb-3 sm:mb-0 sm:mr-4 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-colors",
  resetButton: "w-full sm:w-auto bg-gray-100 hover:bg-gray-200 text-gray-700 font-medium px-6 py-2 rounded-md transition-colors duration-200 border border-gray-300",
  table: "w-full border-collapse bg-white rounded-lg overflow-hidden shadow-sm hidden md:table",
  tableHeader: "bg-gray-100 text-left p-4 font-semibold text-gray-700 border-b border-gray-200 whitespace-nowrap",
  tableRow: "even:bg-gray-50",
  tableCell: "p-4 border-b border-gray-100 text-gray-600 align-top",
  specialtyItem: "mb-1.5 text-sm bg-blue-50 text-blue-700 px-2 py-1 rounded-full inline-block mr-2 last:mr-0",
  mobileCards: "space-y-4 md:hidden",
  mobileCard: "bg-white rounded-lg shadow-sm p-4 border border-gray-100",
  mobileCardField: "flex justify-between py-2 border-b border-gray-100 last:border-0",
  mobileCardLabel: "font-medium text-gray-700",
  mobileCardValue: "text-gray-600 text-right",
  loadingContainer: "flex justify-center items-center h-96 bg-gray-50 rounded-lg",
  errorContainer: "flex justify-center items-center h-96 bg-red-50 rounded-lg",
  noResultsContainer: "flex flex-col justify-center items-center h-96 bg-gray-50 rounded-lg",
  loadingText: "text-gray-600",
  errorText: "text-red-600",
  noResultsText: "text-gray-600 mb-2",
  noResultsSubText: "text-gray-500 text-sm",
  resetLink: "text-blue-500 hover:text-blue-600 underline"
}; 